library(shiny)
shinyUI(fluidPage(
  titlePanel(h1("CART - Classification And Regression Tree")),
  sidebarLayout(position = "left",
    sidebarPanel(
      fileInput("file1",
                accept=c(".csv",".txt"),
                label=h3("1. Data File")),
      selectInput("select0",
                  label ="separated by", 
                  size=1,multiple=F,selectize=F,
                  choices =list("comma (*.csv)"=",","tab (*.txt)"="\t"),
                  selected="comma (*.csv)"),
        p("Comma or tab separated value file can be uploaded and the maximum file size is about 10MB."),
      hr(),
      h3("2. Response Variable"),
      htmlOutput("html1"),
      
        checkboxInput("checkbox0","response as factor",value=FALSE),
        p("Select a response taking continuous or dichotomized or categorical values"),
      hr(),
      h3("3. Explanatory Variables"),
      htmlOutput("html2"),
        p("Select multiple explanatory Variables."),
      hr(),
      h3("4. Option"),
      selectInput("select41",
                  label ="plot a tree - type",
                  size=5, multiple=F, selectize=F,
                  choices=c(
                    "1: All nodes labeled; split above"   = "1",
                    "2: Like 1; split below [CART book]"  = "2",
                    "3: Split labels left / right"         = "3",
                    "4: Like 3; all nodes labeled"        = "4",
                    "5: Like 1; split var. in interior"   = "5"
                  ), selected="5"),
      selectInput("select42",
                  label ="- extra",
                  size=8, multiple=F, selectize=F,
                  choices=c(
                    "0: No extra info"                    = "0",
                    "1: # obs at node"                    = "1",
                    "2: [class] # correct / total"        = "2",
                    "3: [class] # wrong / total"          = "3",
                    "4: [class] Class probs (sum=1/node)" = "4",
                    "5: [class] Like 4, no class label"   = "5",
                    "6: [class] P(2nd class), binary"     = "6",
                    "7: [class] Like 6, no class label"   = "7",
                    "8: [class] P(fitted class)"          = "8",
                    "9: [class] P rel. all obs (sum=1)"   = "9",
                    "10: [class] Like 9, 2nd class"       = "10",
                    "11: [class] Like 10, no label"       = "11",
                    "110: [class] Like 10 + %obs"         = "110"
                  ), selected="1"),
      a(href="https://www.rdocumentation.org/packages/rpart.plot/versions/3.1.0/topics/rpart.plot",
        "see, rpart.plot"),
      checkboxInput("checkbox2","set hyper parameters",value=FALSE),
      sliderInput("numeric1",
                  "minbucket  (rpart default: 7)",
                  min=2, max=500, value=7, step=1),
      p("Minimum number of observations in a terminal node. ",
        "rpart's default of 7 is not data-dependent; ",
        "a common rule of thumb is n/20 ~ n/10 ",
        "(e.g., n=200 → 10~20, n=1000 → 50~100).",
        style="font-size:85%; color:#666; margin-top:-8px;"),
      sliderInput("numeric2",
                  "maxdepth  (rpart default: 30 = no limit)",
                  min=1, max=15, value=5, step=1),
      p("Maximum depth of any node in the final tree (root = depth 0). ",
        "rpart's default of 30 means virtually no constraint; ",
        "trees deeper than 5–7 are rarely interpretable.",
        style="font-size:85%; color:#666; margin-top:-8px;"),
      sliderInput("numeric3",
                  "cp = 10^x  (rpart default: 0.01)",
                  min=-4, max=-1, value=-2, step=0.1),
      uiOutput("cp_display"),
      div(
        "A good choice of cp for pruning of a tree is often the leftmost value",
        " below the horizontal line.",
        a(href="https://www.rdocumentation.org/packages/rpart/versions/4.1-15/topics/plotcp",
        "see, plotcp"),
      ),  
      br(),
      selectInput("select5",
                  label ="train-test split", 
                  size=1,multiple=F,selectize=F,
                  choices =list("100-0%"=1.0,"90-10%"=0.9,"80-20%"=0.8,
                                "70-30%"=0.7,"60-40%"=0.6,"50-50%"=0.5),
                  selected="100-0%"),
      div(
        "Training-Test split for evaluating the prediction accuracy of the model.",
        "If the split ratio is the same, it is reproducible."),
      hr(),
      h3("5. Fit model"),
      actionButton("submit1","Apply..."),
      hr(),
      h3("Example Data Files"),
      # site/CART/data/ を docs/CART/data/ に配置（アプリ本体は CART/app_xxx/ で動くので "../data/"）
      lapply(c("titanic.csv", "iris.csv"),
             function(f) a(href=paste0("../data/", f), download=f, f)),
      p("Both files were created from R's datasets package. ",
        "titanic.csv expands the table 'Titanic' to one row per person ",
        "(Died = 1: did not survive; source: Dawson, 1995, J. Stat. Educ. 3(3)). ",
        "iris.csv is 'iris' (Fisher, 1936, Ann. Eugen. 7, 179-188; ",
        "data collected by Anderson, 1935).",
        style="font-size:85%; color:#666;"),
      hr(),      
      h3("Citation:"),
      div(
        "This system uses 'rpart' function as CART.",
        a(href="https://www.rdocumentation.org/packages/rpart/versions/4.1-15",
          "see, rpart")
      ),
      p(paste0("R Core Team (2024). R: A language and environment for statistical computing. ",
               "R Foundation for Statistical Computing, Vienna, Austria. ",
               "URL https://www.R-project.org/")),
      div(
        "This system also uses 'partykit' for tree visualization.",
        a(href="https://www.jmlr.org/papers/v16/hothorn15a.html","see, partykit"),
      ),
      p(paste0("Hothorn T, Zeileis A (2015). ",
               "partykit: A Modular Toolkit for Recursive Partitioning in R. ",
               "Journal of Machine Learning Research, 16, 3905-3909.")),
      div(
         "This system includes IPA fonts (IPAex Gothic Ver. 004.01)",
         "licensed by CITPC for displaying Japanese.",
         "For details, please refer to the following website.",
         a(href="https://moji.or.jp/ipafont/license/","IPA FONT LICENSE AGREEMENT V1.0")
      ),   
      hr(),      
      h3("Disclaimer:"),      
      p(paste0("This statistical analysis service is experimental. ",
               "It runs entirely in your web browser using Shinylive* and webR**; ",
               "uploaded data files are processed on your computer and are not sent to any server. ",
               "I will not be held responsible for any inconvenience or lost profit ",
               "as a result of the use of this system.")),
      a(href="https://posit-dev.github.io/r-shinylive/","*Shinylive"),
      a(href="https://docs.r-wasm.org/webr/latest/",", **webR"),
      hr(),    
      a(href="https://sites.google.com/view/ksatoh/english/",
        "(C) Prof. Kenichi SATOH, Shiga University, JAPAN"),
      hr()
    ),
    mainPanel(
      verbatimTextOutput('result0'),
      verbatimTextOutput('result1'),
      verbatimTextOutput('result2'),
      h3("Response:"),
      plotOutput('plot0'),
      downloadButton('downloadPlot0', 'PDF'),
      h3("Tree:"),
      plotOutput('plot1'),
      downloadButton('downloadPlot1', 'PDF'),
      h3("Fitting:"),
      plotOutput('plot2'),
      downloadButton('downloadPlot2', 'PDF'),
      downloadButton('download1', 'train'),
      downloadButton('download2', 'test'),
      downloadButton('download3', 'split'),
      h3("Tree (partykit):"),
      plotOutput('plot5'),
      downloadButton('downloadPlot5', 'PNG'),
      h3("Importance"),
      plotOutput('plot3'),
      downloadButton('downloadPlot3', 'PDF'),
      h3("Complexity parameter"),
      plotOutput('plot4'),
      downloadButton('downloadPlot4', 'PDF'),
    )
  )
))
